# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_salerank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salerank',
            name='user',
        ),
        migrations.DeleteModel(
            name='SaleRank',
        ),
    ]
